// Fallback until @mf-types/ is generated by dts: { consumeTypes: true }
declare module "firstApp/App" {
  const App: React.ComponentType
  export default App
}

declare module "secondApp/App" {
  const App: React.ComponentType
  export default App
}
