// Fallback until @mf-types/ is generated by dts: { consumeTypes: true }
declare module "teamApp/App" {
  const App: React.ComponentType
  export default App
}

declare module "monitorApp/App" {
  const App: React.ComponentType
  export default App
}

declare module "settingsApp/App" {
  const App: React.ComponentType
  export default App
}
